# Generated by Django 5.1 on 2024-09-16 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='FloweringCategory',
            fields=[
                ('flowering_id', models.AutoField(primary_key=True, serialize=False)),
                ('flowering', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'FloweringCategories',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(db_column='LocationID', primary_key=True, serialize=False)),
                ('location', models.CharField(db_column='Location', max_length=20)),
            ],
            options={
                'db_table': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('maintenance_id', models.AutoField(db_column='MaintenanceID', primary_key=True, serialize=False)),
                ('maintenance', models.CharField(db_column='Maintenance', max_length=10)),
            ],
            options={
                'db_table': 'MaintenanceTypes',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(db_column='PlantID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('scientific_name', models.CharField(db_column='ScientificName', max_length=150)),
                ('short_description', models.TextField(blank=True, db_column='ShortDescription', null=True)),
                ('watering_frequency', models.CharField(blank=True, db_column='WateringFrequency', max_length=50, null=True)),
                ('watering_schedule', models.TextField(blank=True, db_column='WateringSchedule', null=True)),
                ('soil_type', models.CharField(blank=True, db_column='SoilType', max_length=255, null=True)),
                ('fertilizer_frequency', models.CharField(blank=True, db_column='FertilizerFrequency', max_length=50, null=True)),
                ('photo_url', models.CharField(blank=True, db_column='PhotoURL', max_length=255, null=True)),
                ('category', models.ForeignKey(db_column='CategoryID', on_delete=django.db.models.deletion.CASCADE, to='plants.category')),
                ('flowering_category', models.ForeignKey(db_column='FloweringID', on_delete=django.db.models.deletion.CASCADE, to='plants.floweringcategory')),
                ('location', models.ForeignKey(db_column='LocationID', on_delete=django.db.models.deletion.CASCADE, to='plants.location')),
                ('maintenance_type', models.ForeignKey(db_column='MaintenanceID', on_delete=django.db.models.deletion.CASCADE, to='plants.maintenancetype')),
            ],
            options={
                'db_table': 'Plants',
            },
        ),
        migrations.CreateModel(
            name='PlantNeeds',
            fields=[
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='plants.plant')),
                ('watering_schedule', models.CharField(max_length=255)),
                ('soil_type', models.CharField(max_length=255)),
                ('fertilizer', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'plants_plant_needs',
            },
        ),
    ]
