# Generated by Django 5.1 on 2024-09-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floweringcategory',
            name='flowering_id',
            field=models.AutoField(db_column='FloweringID', primary_key=True, serialize=False),
        ),
    ]
