# Generated by Django 5.1 on 2024-09-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_floweringcategory_flowering_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plant',
            table='PlantsNew',
        ),
    ]
